In [1]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
X = np.array([ [0, 1], [1, 0], [1, 1],[0, 0] ])
y = np.array([ [1], [1], [0], [0]])

In [3]:
model = Sequential()

model.add(Dense(4,input_shape = (2,), activation="relu"))

model.add(Dense(1,activation="softmax"))
model.compile(optimizer="sgd",loss="mse")
#model.build()

In [34]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 4)                 12        
                                                                 
 dense_13 (Dense)            (None, 1)                 5         
                                                                 
Total params: 17
Trainable params: 17
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.fit(x=X, y= y, batch_size=4,epochs=300)

Epoch 1/300
1/1 [==============================] - 0s 279ms/step - loss: 0.5000
Epoch 2/300
1/1 [==============================] - 0s 6ms/step - loss: 0.5000
Epoch 3/300
1/1 [==============================] - 0s 9ms/step - loss: 0.5000
Epoch 4/300
1/1 [==============================] - 0s 7ms/step - loss: 0.5000
Epoch 5/300
1/1 [==============================] - 0s 11ms/step - loss: 0.5000
Epoch 6/300
1/1 [==============================] - 0s 11ms/step - loss: 0.5000
Epoch 7/300
1/1 [==============================] - 0s 12ms/step - loss: 0.5000
Epoch 8/300
1/1 [==============================] - 0s 8ms/step - loss: 0.5000
Epoch 9/300
1/1 [==============================] - 0s 10ms/step - loss: 0.5000
Epoch 10/300
1/1 [==============================] - 0s 8ms/step - loss: 0.5000
Epoch 11/300
1/1 [==============================] - 0s 9ms/step - loss: 0.5000
Epoch 12/300
1/1 [==============================] - 0s 8ms/step - loss: 0.5000
Epoch 13/300
1/1 [==============================] - 0s 

1/1 [==============================] - 0s 12ms/step - loss: 0.5000
Epoch 105/300
1/1 [==============================] - 0s 12ms/step - loss: 0.5000
Epoch 106/300
1/1 [==============================] - 0s 15ms/step - loss: 0.5000
Epoch 107/300
1/1 [==============================] - 0s 12ms/step - loss: 0.5000
Epoch 108/300
1/1 [==============================] - 0s 13ms/step - loss: 0.5000
Epoch 109/300
1/1 [==============================] - 0s 18ms/step - loss: 0.5000
Epoch 110/300
1/1 [==============================] - 0s 20ms/step - loss: 0.5000
Epoch 111/300
1/1 [==============================] - 0s 13ms/step - loss: 0.5000
Epoch 112/300
1/1 [==============================] - 0s 13ms/step - loss: 0.5000
Epoch 113/300
1/1 [==============================] - 0s 11ms/step - loss: 0.5000
Epoch 114/300
1/1 [==============================] - 0s 8ms/step - loss: 0.5000
Epoch 115/300
1/1 [==============================] - 0s 6ms/step - loss: 0.5000
Epoch 116/300
1/1 [=========================

In [36]:
model.save("XOR model1.h5")

In [37]:
print(model.weights)

[<tf.Variable 'dense_12/kernel:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.29029012,  0.6568773 ,  0.3509326 ,  0.2034781 ],
       [-0.24184251, -0.02405548,  0.5541651 ,  0.34402585]],
      dtype=float32)>, <tf.Variable 'dense_12/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>, <tf.Variable 'dense_13/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[-0.8384497],
       [ 0.8123046],
       [ 1.0726521],
       [ 0.7266723]], dtype=float32)>, <tf.Variable 'dense_13/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]


In [38]:
model.weights

[<tf.Variable 'dense_12/kernel:0' shape=(2, 4) dtype=float32, numpy=
 array([[-0.29029012,  0.6568773 ,  0.3509326 ,  0.2034781 ],
        [-0.24184251, -0.02405548,  0.5541651 ,  0.34402585]],
       dtype=float32)>,
 <tf.Variable 'dense_12/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_13/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[-0.8384497],
        [ 0.8123046],
        [ 1.0726521],
        [ 0.7266723]], dtype=float32)>,
 <tf.Variable 'dense_13/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [51]:
len(model.weights)

2